version: "2.1"
services:
  app:
    build: .
    command: npm run start:dev
    environment:
      - PORT=6999
    ports:
      - "6999:6999"
      - "5858:5858"
    volumes:
      - .:/app/
    network_mode: bridge
